version: "3"

services:
  server:
    build: ./server
    ports:
      - "9090:9090"
    container_name: ip4vlookupaip
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: ipv4lookupclient
    